title: Calculating resistor values for LEDs
hero_image: images/banner.png
description: Calculting resistor values for LEDs
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
interests:
technologies: "electronics"
steps:
  - title: Calculating LED resistor values
